# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scholarmarkdown 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "scholarmarkdown"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ruben Taelman"]
  s.date = "2018-04-19"
  s.email = "rubensworks@gmail.com"
  s.executables = ["generate-scholarmd"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.homepage = "http://github.com/rubensworks/ScholarMarkdown"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "A framework for writing markdown-based scholarly articles."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<bibtex-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<latex-decode>, [">= 0"])
      s.add_runtime_dependency(%q<citeproc-ruby>, [">= 1.1.6"])
      s.add_runtime_dependency(%q<csl-styles>, [">= 0"])
      s.add_runtime_dependency(%q<bibmarkdown>, ["~> 1.3.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.4.7"])
    else
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<bibtex-ruby>, [">= 0"])
      s.add_dependency(%q<latex-decode>, [">= 0"])
      s.add_dependency(%q<citeproc-ruby>, [">= 1.1.6"])
      s.add_dependency(%q<csl-styles>, [">= 0"])
      s.add_dependency(%q<bibmarkdown>, ["~> 1.3.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.4.7"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<bibtex-ruby>, [">= 0"])
    s.add_dependency(%q<latex-decode>, [">= 0"])
    s.add_dependency(%q<citeproc-ruby>, [">= 1.1.6"])
    s.add_dependency(%q<csl-styles>, [">= 0"])
    s.add_dependency(%q<bibmarkdown>, ["~> 1.3.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.4.7"])
  end
end

