# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scholarmarkdown 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "scholarmarkdown"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ruben Taelman"]
  s.date = "2018-04-19"
  s.email = "rubensworks@gmail.com"
  s.executables = ["generate-scholarmarkdown"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/template/.gitignore",
    "bin/template/Gemfile",
    "bin/template/Guardfile",
    "bin/template/README.md",
    "bin/template/Rules",
    "bin/template/config.ru",
    "bin/template/content/abstract.md",
    "bin/template/content/index.md.erb",
    "bin/template/content/introduction.md",
    "bin/template/content/references.bib",
    "bin/template/content/styles/lncs.scss",
    "bin/template/content/styles/print.scss",
    "bin/template/content/styles/reset.scss",
    "bin/template/content/styles/screen.scss",
    "bin/template/content/styles/shared.scss",
    "bin/template/layouts/default.html.erb",
    "bin/template/nanoc.yaml",
    "lib/scholarmarkdown.rb",
    "lib/scholarmarkdown/citationstyles/lncs-custom.csl",
    "lib/scholarmarkdown/filter/acronym.rb",
    "lib/scholarmarkdown/filter/citation.rb",
    "lib/scholarmarkdown/filter/headerids_to_section.rb",
    "lib/scholarmarkdown/filter/hyphenate_iri.rb",
    "lib/scholarmarkdown/filter/include_code.rb",
    "lib/scholarmarkdown/filter/labelify.rb",
    "lib/scholarmarkdown/filter/references_to_footer.rb",
    "lib/scholarmarkdown/snippets.rb",
    "scholarmarkdown.gemspec"
  ]
  s.homepage = "http://github.com/rubensworks/ScholarMarkdown"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "A framework for writing markdown-based scholarly articles."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<bibtex-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<latex-decode>, [">= 0"])
      s.add_runtime_dependency(%q<citeproc-ruby>, [">= 1.1.6"])
      s.add_runtime_dependency(%q<csl-styles>, [">= 0"])
      s.add_runtime_dependency(%q<bibmarkdown>, ["~> 1.3.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.4.7"])
    else
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<bibtex-ruby>, [">= 0"])
      s.add_dependency(%q<latex-decode>, [">= 0"])
      s.add_dependency(%q<citeproc-ruby>, [">= 1.1.6"])
      s.add_dependency(%q<csl-styles>, [">= 0"])
      s.add_dependency(%q<bibmarkdown>, ["~> 1.3.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.4.7"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<bibtex-ruby>, [">= 0"])
    s.add_dependency(%q<latex-decode>, [">= 0"])
    s.add_dependency(%q<citeproc-ruby>, [">= 1.1.6"])
    s.add_dependency(%q<csl-styles>, [">= 0"])
    s.add_dependency(%q<bibmarkdown>, ["~> 1.3.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.4.7"])
  end
end

